# Generated by Django 5.1.2 on 2024-11-22 15:06

import annotate.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('annotate', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='upload',
            name='annotatedImage',
            field=models.ImageField(null=True, upload_to='annotated-images/'),
        ),
        migrations.AlterField(
            model_name='upload',
            name='image',
            field=models.ImageField(upload_to=annotate.models.Upload.logo_dir_path),
        ),
    ]
