# Generated by Django 5.1.2 on 2024-11-25 14:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('annotate', '0002_upload_annotatedimage_alter_upload_image'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='upload',
            name='annotatedImage',
        ),
    ]
