# Generated by Django 5.1.2 on 2024-12-04 14:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('annotate', '0003_remove_upload_annotatedimage'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='upload',
            name='title',
        ),
    ]
