# Generated by Django 5.1.2 on 2024-12-04 14:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('annotate', '0004_remove_upload_title'),
    ]

    operations = [
        migrations.AddField(
            model_name='upload',
            name='title',
            field=models.TextField(null=True),
        ),
    ]
