# Generated by Django 5.1.2 on 2024-12-04 14:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('annotate', '0005_upload_title'),
    ]

    operations = [
        migrations.AddField(
            model_name='upload',
            name='annotatedImage',
            field=models.ImageField(null=True, upload_to='ann-images'),
        ),
    ]
