# Generated by Django 5.1.2 on 2024-12-13 14:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('annotate', '0006_upload_annotatedimage'),
    ]

    operations = [
        migrations.AddField(
            model_name='upload',
            name='annotations',
            field=models.TextField(null=True),
        ),
    ]
