# Generated by Django 5.1.2 on 2025-01-31 05:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('annotate', '0007_upload_annotations'),
    ]

    operations = [
        migrations.AddField(
            model_name='upload',
            name='imageLink',
            field=models.TextField(null=True),
        ),
    ]
