# Generated by Django 5.1.2 on 2025-03-14 13:20

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('annotate', '0011_alter_upload_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='upload',
            name='date',
            field=models.DateField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
