# Generated by Django 5.1.2 on 2025-04-04 01:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('annotate', '0012_upload_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='upload',
            name='style',
            field=models.TextField(null=True),
        ),
    ]
