# Generated by Django 5.1.2 on 2025-04-25 01:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('annotate', '0013_upload_style'),
    ]

    operations = [
        migrations.AddField(
            model_name='upload',
            name='gender',
            field=models.TextField(null=True),
        ),
    ]
