// Vocabulary used to power clickable suggestions in the clothing and style
// search bars. Clothing items mirror the annotation classes the backend's
// vision model actually recognizes (see backend/annotate/class_colors.json).
export const CLOTHING_ITEMS = [
  "Jumpsuit",
  "T shirt",
  "aline skirt",
  "bandana",
  "beanie",
  "belt",
  "berets",
  "bomber jacket",
  "boots",
  "box pleat skirt",
  "brimmer hat",
  "button t shirt",
  "camo pants",
  "cap",
  "capris",
  "cardigan",
  "cargo pants",
  "chinos",
  "coat",
  "crewneck",
  "cropped hoodie",
  "cropped t shirt",
  "cropped tank top",
  "dress pants",
  "dress shoes",
  "flannel",
  "flannel shirt",
  "fleece jacket",
  "heels",
  "high boots",
  "high socks",
  "hoodie",
  "jacket",
  "jean jacket",
  "jean shorts",
  "jeans",
  "jersey",
  "jorts",
  "knitted t shirt",
  "leather coat",
  "leather jacket",
  "leather vest",
  "loafer",
  "long skirt",
  "long sleeve",
  "maxi skirt",
  "midi skirt",
  "mini skirt",
  "neck tie",
  "overalls",
  "parachute pants",
  "pencil skirt",
  "plaid pants",
  "pleated pants",
  "polo",
  "puffer jacket",
  "puffer vest",
  "quarter zip",
  "ripped jeans",
  "sandals",
  "scarf",
  "shirt",
  "shorts",
  "skinny",
  "sleeveless shirt",
  "sneaker",
  "suit jacket",
  "suit pants",
  "sunglasses",
  "sweater",
  "sweater vest",
  "sweatpants",
  "tank top",
  "track pants",
  "tracksuit",
  "trousers",
  "tube top",
  "turtleneck",
  "v neck sweater",
  "v neck t shirt",
  "varsity jacket",
  "vest",
  "vinyl pants",
  "windbreaker jacket",
  "winter boots",
  "workwear jacket",
  "workwear pants",
  "zip up",
];

// Mirrors the style categories used to collect training data for the
// Roboflow "outfit-styles" classifier (see scraper/images/*).
export const STYLE_TAGS = [
  "90s hip hop",
  "Casual",
  "Clean",
  "Dark academia",
  "Downtown",
  "Gorpcore",
  "Grunge",
  "Light academia",
  "Old money",
  "Opium",
  "Preppy",
  "Skater",
  "Soft",
  "Star",
  "Streetwear",
  "Surfer",
  "Vintage",
  "Workwear",
];
